#include "GameObject.h"
#include "Application.h"
#include "Camera.h"
#include "Texture.h"
#include <iostream>
#include <cstring> 
#include "Mesh.h"
#include "Menus.h"
#include "Scene.h"
#include "OctreeNode.h" 

GameObject::GameObject(const std::string& path)
{
    // Distinguish between a loaded model and a geometry generated by our library.
    if (path != "NULL" && path != "Imported") loadModel(path);
    else 
    {
        position = { 0,0,0 };
        rotation = { 0,0,0 };
        scale = { 1,1,1 };

        worldPosition = { 0,0,0 };
        worldRotation = { 0,0,0 };
        worldScale = { 1,1,1 };

        minAABB = { -1,-1,-1 };
        maxAABB = { 1,1,1 };
        //UpdateTransform();
    }
}
void GameObject::ApplTexture(Texture* tex, std::string path)
{
    Mmesh.texture = tex;
    actualTexture = tex;
    texturePath = path;
    //hasTransparency = tex->hasAlpha;

    if (tex != nullptr)
    {
        hasTransparency = tex->hasAlpha;
    }
    else
    {
        hasTransparency = false;
    }
}
// Draw all meshes of the model
void GameObject::Draw()
{

    if (isHidden) return;

    GLuint shaderProgram = Application::GetInstance().render->shaderProgram;

    if (hasTransparency) {
        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        glDepthMask(GL_FALSE);
    }
        
    else {
        glDisable(GL_BLEND);
        glDepthMask(GL_TRUE);
    }

    // Send the transformation matrix to the shader
    GLint modelLoc = glGetUniformLocation(shaderProgram, "model_matrix");
    glUniformMatrix4fv(modelLoc, 1, GL_FALSE, glm::value_ptr(transformMatrix));
    
    if (Mmesh.texture)
    {
        Mmesh.texture->texUnit(shaderProgram, "tex0", 0);
        Mmesh.texture->Bind();
        GLint useTexLoc = glGetUniformLocation(shaderProgram, "useTexture");

        glUniform1i(useTexLoc, 1);
    }
    else
    {
        GLint useTexLoc = glGetUniformLocation(shaderProgram, "useTexture");
        glUniform1i(useTexLoc, 0);
    }
 
    glm::vec4 overrideColorVec(0.0f, 0.0f, 0.0f, 0.0f); // default: no override

    // Draw all meshes
    glBindVertexArray(Mmesh.VAO);

    if (name != "Grid") glDrawElements(GL_TRIANGLES, Mmesh.indexCount, GL_UNSIGNED_INT, 0);
    else glDrawElements(GL_LINES, Mmesh.indexCount, GL_UNSIGNED_INT, 0);

    glBindVertexArray(0);

    if (Mmesh.texture)
        Mmesh.texture->Unbind();

    glDepthMask(GL_TRUE);
    glDisable(GL_BLEND);
}

void GameObject::UpdateAABB()
{
    glm::vec3 worldMin(std::numeric_limits<float>::max());
    glm::vec3 worldMax(std::numeric_limits<float>::lowest());

    for (int i = 0; i < 8; ++i)
    {
        glm::vec3 corner(
            (i & 1) ? localMaxAABB.x : localMinAABB.x,
            (i & 2) ? localMaxAABB.y : localMinAABB.y,
            (i & 4) ? localMaxAABB.z : localMinAABB.z
        );

        glm::vec4 transformed = transformMatrix * glm::vec4(corner, 1.0f);
        glm::vec3 p = glm::vec3(transformed);

        worldMin = glm::min(worldMin, p);
        worldMax = glm::max(worldMax, p);
    }

    minAABB = worldMin;
    maxAABB = worldMax;
    center = (worldMin + worldMax) * 0.5f;
    size = worldMax - worldMin;
}

void GameObject::UpdateTransform()
{
    for (int x = 0; x < childrenID.size(); x++) 
        Application::GetInstance().scene.get()->models[childrenID[x]].UpdateTransform();

    localMatrix = glm::mat4(1.0f);
    localMatrix = glm::translate(localMatrix, position);
    localMatrix = glm::rotate(localMatrix, glm::radians(rotation.z), glm::vec3(0, 0, 1));
    localMatrix = glm::rotate(localMatrix, glm::radians(rotation.y), glm::vec3(0, 1, 0));
    localMatrix = glm::rotate(localMatrix, glm::radians(rotation.x), glm::vec3(1, 0, 0));
    localMatrix = glm::scale(localMatrix, scale);

    if (isChild)
    {
        transformMatrix = Application::GetInstance().scene->models[ParentID].transformMatrix * localMatrix;
        parentTransform = false;
    }
    else
    {
        transformMatrix = localMatrix;
    }

    float translation[3], rotationDeg[3], scaleArr[3];
    ImGuizmo::DecomposeMatrixToComponents(glm::value_ptr(transformMatrix), translation, rotationDeg, scaleArr);

    worldPosition = glm::vec3(translation[0], translation[1], translation[2]);

    worldRotation = glm::vec3(rotationDeg[0], rotationDeg[1], rotationDeg[2]);

    worldScale = glm::vec3(scaleArr[0], scaleArr[1], scaleArr[2]);

    // Usa los bounds LOCALES para calcular la caja en mundo
    glm::vec3 corners[8] =
    {
        {localMinAABB.x, localMinAABB.y, localMinAABB.z},
        {localMinAABB.x, localMinAABB.y, localMaxAABB.z},
        {localMinAABB.x, localMaxAABB.y, localMinAABB.z},
        {localMinAABB.x, localMaxAABB.y, localMaxAABB.z},
        {localMaxAABB.x, localMinAABB.y, localMinAABB.z},
        {localMaxAABB.x, localMinAABB.y, localMaxAABB.z},
        {localMaxAABB.x, localMaxAABB.y, localMinAABB.z},
        {localMaxAABB.x, localMaxAABB.y, localMaxAABB.z},
    };

    glm::vec3 newMin(FLT_MAX);
    glm::vec3 newMax(-FLT_MAX);

    for (int i = 0; i < 8; ++i)
    {
        glm::vec4 transformed = transformMatrix * glm::vec4(corners[i], 1.0f);
        glm::vec3 p = glm::vec3(transformed);
        newMin = glm::min(newMin, p);
        newMax = glm::max(newMax, p);
    }

    center = (newMin + newMax) * 0.5f;
    size = newMax - newMin;

    // Actualiza posiciones mundiales
   
    Mmesh.positionsWorld.resize(Mmesh.positionsLocal.size());
    for (size_t i = 0; i < Mmesh.positionsLocal.size(); ++i) {
        glm::vec4 p = transformMatrix * glm::vec4(Mmesh.positionsLocal[i], 1.0f);
        Mmesh.positionsWorld[i] = glm::vec3(p);
    }
    // Actualiza AABB mundo usando los bounds locales (funci�n ya existente)
    UpdateAABB();
}

// Load a model using Assimp
void GameObject::loadModel(const std::string& path)
{

    directory = path.substr(0, path.find_last_of('/'));

    name = path.substr(path.find_last_of("/\\") + 1);
    name = name.substr(0, name.find_last_of('.'));

    modelPath = "../Library/Meshes/" + name + ".txt";

    //processNode(scene->mRootNode, scene);
    Application::GetInstance().mesh.get()->loadModel(path, this);

    //processOthers(scene);
    center = (minAABB + maxAABB) * 0.5f;
    size = maxAABB - minAABB;

    localMinAABB = minAABB;
    localMaxAABB = maxAABB;

    position = { 0,0,0 };
    rotation = { 0,0,0 };
    scale = { 1,1,1 };

    if (!Application::GetInstance().scene->octreeRoot) {
        Application::GetInstance().scene->BuildOctree();
    }
    else {
        OctreeNode* root = Application::GetInstance().scene->octreeRoot.get();
        root->Insert(&Application::GetInstance().scene->models.back());
    }
    blackWhite = new Texture("../Images/BlancoNegro.png", GL_TEXTURE_2D, GL_TEXTURE0, GL_RGBA, GL_UNSIGNED_BYTE);
    
    UpdateTransform();
    UpdateAABB();

}
// Switch the model's texture (BlackWhite or NormalMap)
void GameObject::switchTexture(bool checker, std::string type)
{
    Texture* tempTex;
    if (type == "BlackWhite")
    {
        if (checker) tempTex = blackWhite;
        else tempTex = actualTexture;
    }
    if (type == "Hide")
    {
        if (checker) tempTex = noTexture;
        else tempTex = actualTexture;
    }
    Mmesh.texture = tempTex;
}

// Get the model matrix
glm::mat4 GameObject::GetModelMatrix() const {
    return transformMatrix;
}
void GameObject::SetChild(GameObject* child)
{
    if (child->ParentID == modelId)
        return;
    for (int x = 0; x < child->childrenID.size(); x++)
    {
        if (child->childrenID[x] == modelId) return;
    }

    if (child->isChild) {
        Application::GetInstance().scene->models[child->ParentID].eraseChild(child->modelId);
    }

    childrenID.push_back(child->modelId);
    child->isChild = true;
    child->ParentID = modelId;

    child->UpdateTransform();
}
void  GameObject::eraseChild(int childId)
{
    childrenID.erase(std::remove(childrenID.begin(), childrenID.end(), childId),childrenID.end());
}
// Cleanup all OpenGL buffers and textures
void  GameObject::CleanUpChilds()
{
    auto childCopy = childrenID; // copia segura
    for (int childId : childCopy)
    {
        // Solo borrar si realmente sigue siendo hijo tuyo
        if (Application::GetInstance().scene->models[childId].ParentID == modelId)
        {
            Application::GetInstance().scene->models[childId].CleanUpChilds();

            // borrar del vector childrenID
            eraseChild(childId);

            // borrar del sceneModels
            auto& sceneModels = Application::GetInstance().scene->models;
            sceneModels.erase(
                std::remove_if(sceneModels.begin(), sceneModels.end(),
                    [&](const GameObject& m) { return m.modelId == childId; }),
                sceneModels.end()
            );
        }
    }   
}

void GameObject::SaveInitialState() {
    initial_position = position;
    initial_rotation = rotation;
    initial_scale = scale;
    initial_isHidden = isHidden;
    initial_texturePath = texturePath;
    created_in_play = false;
    initial_modelPath = modelPath;
    initial_ParentID = ParentID;
}

void GameObject::LoadInitialState() {
    position = initial_position;
    rotation = initial_rotation;
    scale = initial_scale;
    isHidden = initial_isHidden;
    modelPath = initial_modelPath;
    texturePath = initial_texturePath;
    UpdateTransform();

}

glm::vec3 GameObject::GetInitialPosition() const
{
    return initial_position;
}

glm::vec3 GameObject::GetInitialRotation() const
{
    return initial_rotation;
}

glm::vec3 GameObject::GetInitialScale() const
{
    return initial_scale;
}

std::string GameObject::GetInitialTexturePath() const
{
    return initial_texturePath;
}

bool GameObject::GetInitialIsHidden() const
{
    return initial_isHidden;
}

int GameObject::GetInitialParentID() const
{
    return initial_ParentID;
}

void GameObject::SetInitialParentID(int id)
{
    initial_ParentID = id;
}

void GameObject::CleanUp()
{
    if (Mmesh.VAO != 0)
        glDeleteVertexArrays(1, &Mmesh.VAO);
    if (Mmesh.VBO != 0)
        glDeleteBuffers(1, &Mmesh.VBO);
    if (Mmesh.EBO != 0)
        glDeleteBuffers(1, &Mmesh.EBO);
    if (Mmesh.texture)
        delete Mmesh.texture;
    if (blackWhite)
        delete blackWhite;

    Mmesh.VAO = 0;
    Mmesh.VBO = 0;
    Mmesh.EBO = 0;

    Mmesh.texture = nullptr;
    actualTexture = nullptr;
    blackWhite = nullptr;
}

void GameObject::RecreateBuffers() {
    if (Mmesh.VAO != 0) glDeleteVertexArrays(1, &Mmesh.VAO);
    if (Mmesh.VBO != 0) glDeleteBuffers(1, &Mmesh.VBO);
    if (Mmesh.EBO != 0) glDeleteBuffers(1, &Mmesh.EBO);

    glGenVertexArrays(1, &Mmesh.VAO);
    glGenBuffers(1, &Mmesh.VBO);
    glGenBuffers(1, &Mmesh.EBO);

    glBindVertexArray(Mmesh.VAO);

    glBindBuffer(GL_ARRAY_BUFFER, Mmesh.VBO);
    glBufferData(GL_ARRAY_BUFFER, Mmesh.positionsLocal.size() * sizeof(glm::vec3),
        Mmesh.positionsLocal.data(), GL_STATIC_DRAW);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, Mmesh.EBO);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, Mmesh.indices.size() * sizeof(unsigned int),
        Mmesh.indices.data(), GL_STATIC_DRAW);

    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(glm::vec3), (void*)0);

    glBindVertexArray(0);
}
