#include "Model.h"
#include "Application.h"
#include "Camera.h"
#include "Texture.h"
#include <iostream>
#include <cstring> 
#include "Menus.h"
#include "Scene.h"
#include "OctreeNode.h"

Model::Model(const std::string& path)
{
    // Distinguish between a loaded model and a geometry generated by our library.
    if (path != "NULL") loadModel(path);
    else 
    {
        position = { 0,0,0 };
        rotation = { 0,0,0 };
        scale = { 1,1,1 };

        minAABB = { -1,-1,-1 };
        maxAABB = { 1,1,1 };
        UpdateTransform();
    }

    blackWhite = new Texture("../Images/BlancoNegro.png", GL_TEXTURE_2D, GL_TEXTURE0, GL_RGBA, GL_UNSIGNED_BYTE);
}

// Draw all meshes of the model
void Model::Draw()
{
    if (isHidden) return;
   
    GLuint shaderProgram = Application::GetInstance().render->shaderProgram;

    if (hasTransparency) {
        glEnable(GL_BLEND);
        glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
        glDepthMask(GL_FALSE);
    }
        
    else {
        glDisable(GL_BLEND);
        glDepthMask(GL_TRUE);
    }



    // Send the transformation matrix to the shader
    GLint modelLoc = glGetUniformLocation(shaderProgram, "model_matrix");
    glUniformMatrix4fv(modelLoc, 1, GL_FALSE, glm::value_ptr(transformMatrix));

    if (Mmesh.texture)
    {
        Mmesh.texture->texUnit(shaderProgram, "tex0", 0);
        Mmesh.texture->Bind();
        GLint useTexLoc = glGetUniformLocation(shaderProgram, "useTexture");
        glUniform1i(useTexLoc, 1);
    }
    else
    {
        GLint useTexLoc = glGetUniformLocation(shaderProgram, "useTexture");
        glUniform1i(useTexLoc, 0);
    }

    // Draw all meshes
    glBindVertexArray(Mmesh.VAO);

    if (name != "Grid") glDrawElements(GL_TRIANGLES, Mmesh.indexCount, GL_UNSIGNED_INT, 0);
    else glDrawElements(GL_LINES, Mmesh.indexCount, GL_UNSIGNED_INT, 0);

    glBindVertexArray(0);

    if (Mmesh.texture)
        Mmesh.texture->Unbind();

    glDepthMask(GL_TRUE);
    glDisable(GL_BLEND);
}

void Model::UpdateAABB()
{
    glm::vec3 worldMin(std::numeric_limits<float>::max());
    glm::vec3 worldMax(std::numeric_limits<float>::lowest());

    for (int i = 0; i < 8; ++i)
    {
        glm::vec3 corner(
            (i & 1) ? localMaxAABB.x : localMinAABB.x,
            (i & 2) ? localMaxAABB.y : localMinAABB.y,
            (i & 4) ? localMaxAABB.z : localMinAABB.z
        );

        glm::vec4 transformed = transformMatrix * glm::vec4(corner, 1.0f);
        glm::vec3 p = glm::vec3(transformed);

        worldMin = glm::min(worldMin, p);
        worldMax = glm::max(worldMax, p);
    }

    minAABB = worldMin;
    maxAABB = worldMax;
    center = (worldMin + worldMax) * 0.5f;
    size = worldMax - worldMin;
}

void Model::UpdateTransform()
{
    transformMatrix = glm::mat4(1.0f);
    transformMatrix = glm::translate(transformMatrix, position);
    transformMatrix = glm::rotate(transformMatrix, glm::radians(rotation.z), glm::vec3(0, 0, 1));
    transformMatrix = glm::rotate(transformMatrix, glm::radians(rotation.y), glm::vec3(0, 1, 0));
    transformMatrix = glm::rotate(transformMatrix, glm::radians(rotation.x), glm::vec3(1, 0, 0));
    transformMatrix = glm::scale(transformMatrix, scale);

    // Usa los bounds LOCALES para calcular la caja en mundo
    glm::vec3 corners[8] =
    {
        {localMinAABB.x, localMinAABB.y, localMinAABB.z},
        {localMinAABB.x, localMinAABB.y, localMaxAABB.z},
        {localMinAABB.x, localMaxAABB.y, localMinAABB.z},
        {localMinAABB.x, localMaxAABB.y, localMaxAABB.z},
        {localMaxAABB.x, localMinAABB.y, localMinAABB.z},
        {localMaxAABB.x, localMinAABB.y, localMaxAABB.z},
        {localMaxAABB.x, localMaxAABB.y, localMinAABB.z},
        {localMaxAABB.x, localMaxAABB.y, localMaxAABB.z},
    };

    glm::vec3 newMin(FLT_MAX);
    glm::vec3 newMax(-FLT_MAX);

    for (int i = 0; i < 8; ++i)
    {
        glm::vec4 transformed = transformMatrix * glm::vec4(corners[i], 1.0f);
        glm::vec3 p = glm::vec3(transformed);
        newMin = glm::min(newMin, p);
        newMax = glm::max(newMax, p);
    }

    center = (newMin + newMax) * 0.5f;
    size = newMax - newMin;

    // Actualiza posiciones mundiales
    Mmesh.positionsWorld.resize(Mmesh.positionsLocal.size());
    for (size_t i = 0; i < Mmesh.positionsLocal.size(); ++i) {
        glm::vec4 p = transformMatrix * glm::vec4(Mmesh.positionsLocal[i], 1.0f);
        Mmesh.positionsWorld[i] = glm::vec3(p);
    }

    // Actualiza AABB mundo usando los bounds locales (función ya existente)
    UpdateAABB();
}

// Load a model using Assimp
void Model::loadModel(const std::string& path)
{
    Assimp::Importer importer;
    const aiScene* scene = importer.ReadFile(path,
        aiProcess_Triangulate |
        aiProcess_FlipUVs |
        aiProcess_CalcTangentSpace |
        aiProcess_GenNormals
    );

    if (!scene || scene->mFlags & AI_SCENE_FLAGS_INCOMPLETE || !scene->mRootNode)
    {
        std::cerr << "ERROR::ASSIMP::" << importer.GetErrorString() << std::endl;
        Application::GetInstance().menus->LogToConsole(std::string("ERROR: FBX load failed: ") + path);
        Application::GetInstance().menus->LogToConsole(std::string("ERROR: Assimp load failed: ") + importer.GetErrorString());
        return;
    }
    else 
    {
        Application::GetInstance().menus->LogToConsole("Loaded FBX: " + path);
        Application::GetInstance().menus->LogToConsole("ASSIMP initialized");
    }

    directory = path.substr(0, path.find_last_of('/'));

    name = path.substr(path.find_last_of("/\\") + 1);
    name = name.substr(0, name.find_last_of('.'));

    processNode(scene->mRootNode, scene);
    center = (minAABB + maxAABB) * 0.5f;
    size = maxAABB - minAABB;

    position = { 0,0,0 };
    rotation = { 0,0,0 };
    scale = { 1,1,1 };

    UpdateTransform();
    if (Application::GetInstance().scene->octreeRoot) {
        OctreeNode* root = Application::GetInstance().scene->octreeRoot.get();
        root->Insert(&Application::GetInstance().scene->models.back());
    }
}

// Process all meshes in a node
void Model::processNode(aiNode* node, const aiScene* scene)
{
    for (unsigned int i = 0; i < node->mNumMeshes; i++)
    {
        aiMesh* mesh = scene->mMeshes[node->mMeshes[i]];
        processMesh(mesh, scene);
    }

    // Recursively process child nodes
    for (unsigned int i = 0; i < node->mNumChildren; i++)
        processNode(node->mChildren[i], scene);
}

// Convert an aiMesh from Assimp into a ModelMesh with VAO/VBO/EBO
void Model::processMesh(aiMesh* mesh, const aiScene* scene)
{
    std::vector<float> vertices;
    std::vector<unsigned int> indices;
    minAABB = glm::vec3(FLT_MAX);
    maxAABB = glm::vec3(-FLT_MAX);

    Mmesh.positionsLocal.clear();
    Mmesh.indices.clear();

    // Extract vertices: position, normal, and UV coordinates
    for (unsigned int i = 0; i < mesh->mNumVertices; i++)
    {
        glm::vec3 vertex(mesh->mVertices[i].x,
            mesh->mVertices[i].y,
            mesh->mVertices[i].z);

        // Update AABB
        minAABB = glm::min(minAABB, vertex);
        maxAABB = glm::max(maxAABB, vertex);

        Mmesh.positionsLocal.push_back(vertex);
      
        // Position
        vertices.push_back(mesh->mVertices[i].x);
        vertices.push_back(mesh->mVertices[i].y);
        vertices.push_back(mesh->mVertices[i].z);


        // Normal
        vertices.push_back(mesh->mNormals[i].x);
        vertices.push_back(mesh->mNormals[i].y);
        vertices.push_back(mesh->mNormals[i].z);

        // Texture UV
        if (mesh->mTextureCoords[0])
        {
            vertices.push_back(mesh->mTextureCoords[0][i].x);
            vertices.push_back(mesh->mTextureCoords[0][i].y);
        }
        else
        {
            vertices.push_back(0.0f);
            vertices.push_back(0.0f);
        }
    }

    localMinAABB = minAABB;
    localMaxAABB = maxAABB;

    // Extract tangents if available
    if (mesh->mTangents != nullptr) 
    {
        hasTangents = true;
        tangents.clear();
        for (unsigned int i = 0; i < mesh->mNumVertices; i++) 
        {
            tangents.push_back(glm::vec3(mesh->mTangents[i].x,
                mesh->mTangents[i].y,
                mesh->mTangents[i].z));
        }
    }

    // Extract bitangents if available
    if (mesh->mBitangents != nullptr) {
        hasBitangents = true;
        bitangents.clear();
        for (unsigned int i = 0; i < mesh->mNumVertices; i++) {
            bitangents.push_back(glm::vec3(mesh->mBitangents[i].x,
                mesh->mBitangents[i].y,
                mesh->mBitangents[i].z));
        }
    }

    // Extract indices
    for (unsigned int i = 0; i < mesh->mNumFaces; i++)
    {
        aiFace face = mesh->mFaces[i];
        for (unsigned int j = 0; j < face.mNumIndices; j++) {
            indices.push_back(face.mIndices[j]);
            Mmesh.indices.push_back(face.mIndices[j]);
        }
           
    }
    // Draw vertex and face normals for debugging
    VertexNormalmesh = Application::GetInstance().render.get()->DrawVertexNormalsFromMesh(vertices.data(), vertices.size(), tangents, bitangents, {}, vertexNormalLines);
    Normalmesh = Application::GetInstance().render.get()->DrawFaceNormals(vertices.data(), indices.data(), indices.size(), normalLines);

    // Create OpenGL buffers
    glGenVertexArrays(1, &Mmesh.VAO);
    glGenBuffers(1, &Mmesh.VBO);
    glGenBuffers(1, &Mmesh.EBO);

    glBindVertexArray(Mmesh.VAO);

    glBindBuffer(GL_ARRAY_BUFFER, Mmesh.VBO);
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(float), vertices.data(), GL_STATIC_DRAW);

    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, Mmesh.EBO);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), indices.data(), GL_STATIC_DRAW);

    // Position attribute
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, 8 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(0);

    // Normal attribute
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, 8 * sizeof(float), (void*)(3 * sizeof(float)));
    glEnableVertexAttribArray(1);

    // Texture attribute
    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, 8 * sizeof(float), (void*)(6 * sizeof(float)));
    glEnableVertexAttribArray(2);

    //// Alpha
    //glVertexAttribPointer(3, 1, GL_FLOAT, GL_FALSE, 9 * sizeof(float), (void*)(8 * sizeof(float)));
    //glEnableVertexAttribArray(3);

    glBindVertexArray(0);

    Mmesh.indexCount = indices.size();

    // Load texture from material if available
    if (mesh->mMaterialIndex >= 0)
    {
        aiMaterial* material = scene->mMaterials[mesh->mMaterialIndex];
        aiString path;
        if (material->GetTexture(aiTextureType_DIFFUSE, 0, &path) == AI_SUCCESS)
        {
            std::string filename = std::string(path.C_Str());

            // Normalize backslashes
            std::replace(filename.begin(), filename.end(), '\\', '/');

            // If the texture path is not absolute, prepend the model directory
            if (filename[0] != '/' && !(filename.length() > 1 && filename[1] == ':'))
                filename = directory + "/" + filename;

            std::cout << "Loading texture from material: " << filename << std::endl;

            Mmesh.texture = new Texture(filename.c_str(), GL_TEXTURE_2D, GL_TEXTURE0, GL_RGBA, GL_UNSIGNED_BYTE);
          
            if (Mmesh.texture)
                hasTransparency = Mmesh.texture->hasAlpha;

        }
        else
        {
            std::cout << "No diffuse texture found in the material." << std::endl;
            Mmesh.texture = nullptr;
            hasTransparency = false;

        }
    }
}

// Switch the model's texture (BlackWhite or NormalMap)
void Model::switchTexture(bool checker, std::string type)
{
    if (type == "BlackWhite")
    {
        if (checker) Mmesh.texture = blackWhite;
        else Mmesh.texture = actualTexture;
    }
    if (type == "Hide")
    {
        if (checker) Mmesh.texture = noTexture;
        else Mmesh.texture = actualTexture;
    }
}

// Get the model matrix
glm::mat4 Model::GetModelMatrix() const {
    glm::mat4 trans = glm::translate(glm::mat4(1.0f), position);
    glm::mat4 rotX = glm::rotate(glm::mat4(1.0f), glm::radians(rotation.x), glm::vec3(1, 0, 0));
    glm::mat4 rotY = glm::rotate(glm::mat4(1.0f), glm::radians(rotation.y), glm::vec3(0, 1, 0));
    glm::mat4 rotZ = glm::rotate(glm::mat4(1.0f), glm::radians(rotation.z), glm::vec3(0, 0, 1));
    glm::mat4 scaleMat = glm::scale(glm::mat4(1.0f), scale);
    return trans * rotZ * rotY * rotX * scaleMat;
}

// Cleanup all OpenGL buffers and textures
void Model::CleanUp()
{
    if (Mmesh.VAO != 0)
        glDeleteVertexArrays(1, &Mmesh.VAO);
    if (Mmesh.VBO != 0)
        glDeleteBuffers(1, &Mmesh.VBO);
    if (Mmesh.EBO != 0)
        glDeleteBuffers(1, &Mmesh.EBO);
    if (Mmesh.texture)
        delete Mmesh.texture;
    if (blackWhite)
        delete blackWhite;

    Mmesh.VAO = 0;
    Mmesh.VBO = 0;
    Mmesh.EBO = 0;

    Mmesh.texture = nullptr;
    actualTexture = nullptr;
    blackWhite = nullptr;
}